= Terminologies

Below is a brief description of a few key terminologies used in this developer guide.

*OpenTraining:*

OpenTraining is a program that enables subject matter experts (SMEs) within the organization to share their knowledge and expertise both internally and externally. SMEs use the tools and processes provided by the training team to create hands-on technical training content. After the SME develops the content, the training team performs testing and quality checks on the labs and materials, ensuring a smooth and rapid onboarding of the training.

*RedHat QuickCourse:*

RedHat QuickCourse is an Asciidoctor documentation toolchain based on https://antora.org/[the Antora project]. RedHat employees can work with the training team to use the github repositories under this project on github.

RedHat QuickCourse is an Asciidoctor documentation toolchain built on the https://antora.org/[Antora project]. RedHat employees can collaborate with the training team to utilize the https://github.com/orgs/RedHatQuickCourses/repositories[GitHub repositories under this project] for content development.

*RHDP labs:*

https://demo.redhat.com/[RHDP (Red Hat Demo Platform)] is a lab environment offering provided by Red Hat for its associates and partners. The lab environments on this platform are built using the https://redhat-cop.github.io/agnosticd/[AgnosticD] project, an Ansible-based deployment tool for multiple cloud environments.

*ROLE labs:*

ROLE (Red Hat Online Learning) is a lab environment offering provided by Red Hat for its associates and partners. This platform is primarily used for Red Hat certification courses and other shorter training programs offered by Red Hat.


